/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zadanie.java;

public class IFSApp {

    public static void main(String[] args) {
        IFSService IFS = new IFSService();
        IFS.run(args);
    }
}
